# Generated by Django 3.1.3 on 2020-11-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='description',
            field=models.CharField(default='description', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superhero',
            name='strength',
            field=models.CharField(default='strength', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superhero',
            name='weakness',
            field=models.CharField(default='weakness', max_length=20),
            preserve_default=False,
        ),
    ]
